# fly.toml app configuration file generated for personal-website-rag-dry-night-3555 on 2025-02-11T17:05:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-website-rag-dry-night-3555'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
